from .stl.stl_model import STLTrendinessDetector
from .ma_seasonal.ma_seasonal_model import MovingAverageSeasonalTrendinessDetector
from .twitter.twitter_trendiness_detector import TwitterAnomalyTrendinessDetector
from .lstm.lstm_anomaly import LSTMTrendinessDetector
from .azure_anomaly_detection.azure_ad import AzureAnomalyTrendinessDetector
