from moda.models.stl.stl_model import STLTrendinessDetector
from moda.models.ma_seasonal.ma_seasonal_model import MovingAverageSeasonalTrendinessDetector
from moda.models.twitter.twitter_trendiness_detector import TwitterAnomalyTrendinessDetector
from moda.models.lstm.lstm_anomaly import LSTMTrendinessDetector
from moda.models.azure_anomaly_detection.azure_ad import AzureAnomalyTrendinessDetector
